### ISSUE TITLE
Nothing is happening when "--service vpc"

### ISSUE THREAD

**Issue by Louzogh** [JohannesEbke/aws_list_all#10]
is it a personal or general problem?

my goal here is to retrieve information about the "internet gateway" service

**Comment by JohannesEbke** [comment]
Hi @Louzogh , the services here are extracted from the boto3 services, which are the same as in the aws CLI.

The resources in the "VPC" tab in the amazon web console, including internet gateways, are however lumped in the "ec2" service from the API; so you should be able to see them with --service "ec2"

**Comment by Louzogh** [comment]
Hi @JohannesEbke 

Good ! :laughing: 
Thank you for the answer !
