### ISSUE TITLE
Support for Profile

### ISSUE THREAD

**Issue by tmtiwari** [JohannesEbke/aws_list_all#11]
Currently it only works with the [default] profile credentials. Please provide support for using a different profile from ~/.aws/credentials.

In general we have multiple profiles for different accounts for different purposes.

**Comment by JohannesEbke** [comment]
Hi @tmtiwari , in general you can use AWS_PROFILE to select the profile you want to use with boto3 (see [Boto3 Docs](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html).
I guess it would be nice to have a --profile option too, I'd be open for pull requests.

**Comment by alexjmoore** [comment]
I just submitted PR #28 as a first attempt to address this.  Needs a bit of checking as its failing tests, but I have commented on it.

**Comment by JohannesEbke** [comment]
Fixed by merging #28
