### ISSUE TITLE
aws_list_all: error: argument COMMAND: invalid choice: 'eu-west-1' (choose from 'query', 'show', 'introspect', 'recreate-caches')

### ISSUE THREAD

**Issue by mydigia** [JohannesEbke/aws_list_all#18]
Hello,

I have a few issues:

1) Running
`aws-list-all --region eu-west-1 --service s3 --directory ./data/`

Returns:
`usage: aws_list_all [-h] COMMAND ...
aws_list_all: error: argument COMMAND: invalid choice: 'eu-west-1' (choose from 'query', 'show', 'introspect', 'recreate-caches')`

2) Is there a way I can pull all resources (all regardless of the service) with all theirs tags & IDs? This is to create a manifest which can then be used for bulk tagging.

**Comment by JohannesEbke** [comment]
Hi @mydigia,

1. Thanks to @tjmcewan the typo that led you to the error was fixed now; if you try again with "query" it should work.

2. aws-list-all tries to call all listing operations and saves the return values (including IDs) as JSON. "aws-list-all show -v [<json files>]" will try to list the IDs of the respective resources. For even more information, you can look directly at the saved json files. Unfortunately, tagging is not unified across AWS services, so unless the tag is in the listing (rare), this would need additional work.
