### ISSUE TITLE
Application stops at "Executing queries" and does nothing

### ISSUE THREAD

**Issue by mattolenik** [JohannesEbke/aws_list_all#24]
I cannot execute any query against any service. This is always what happens:

```
aws-list-all query --region eu-west-1 --service ec2 --operation DescribeVpcs --verbose
Building set of queries to execute...
Service: ec2                          | Region: eu-west-1       | Operation: DescribeVpcs
...done. Executing queries...
```

Regardless of operation or service, it just hangs. I've let it run for hours with no progress.

**Comment by michael-paddle** [comment]
@mattolenik it "works for me" with the exact same arguments and within a few second - though in a situation where it's not outputting data.  Changing to a region where I actually have VPCs also works and gives data.  

Could you please try with the verbose argument twice?  

```
aws-list-all query  --verbose --region us-east-1 --service ec2 --operation DescribeVpcs
```

that gives me extra output with details of calls made which might be helpful.

**Comment by mattolenik** [comment]
That's exactly what I did, I used the `--verbose` flag. I tried moving `--verbose` to immediately after `query` and it made no difference. I have VPCs in this region and I can list them with the CLI just fine. It simply hangs

**Comment by mattolenik** [comment]
It works when I install from master

**Comment by JohannesEbke** [comment]
I've updated PyPI with the latest version; so it should work now. You may have hit #7 . If you have v0.7.3, it should not occur again, if it does, please reopen!

**Comment by JohannesEbke** [comment]
Thanks @michael-paddle for the support :)
