### ISSUE TITLE
CloudFormation error in eu-north-1 where stacksets cannot be queried

### ISSUE THREAD

**Issue by jon-frame** [JohannesEbke/aws_list_all#26]
Error: 

cloudformation eu-north-1 ListStackSets ClientError('An error occurred (ValidationError) when calling the ListStackSets operation: AWS CloudFormation StackSets is not supported in eu-north-1')

**Comment by JohannesEbke** [comment]
Well, it seems that it is now supported. Generally: These types of errors will crop up now and again, if they are annoying and show that no resources are used I can add them to https://github.com/JohannesEbke/aws_list_all/blob/master/aws_list_all/query.py#L29 to be ignored.
