### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by starty1314** [JohannesEbke/aws_list_all#29]
Hi Johannes,

Sorry to bother you, but I am curious how you generated the list of service and regions. I found the the links below in google, but It's a bit of challenging to scrape the data from them.

Do you have any secret souce?

**Comment by starty1314** [comment]
https://docs.aws.amazon.com/general/latest/gr/rande.html#endpoint-tables

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/

**Comment by JohannesEbke** [comment]
Hi @starty1314 , I'm using the meta-information from boto3, the official python SDK from AWS.
That one includes a machine-readable description, e.g. at:
`boto3.client('s3').meta.service_model.operation_names`, see at
https://github.com/JohannesEbke/aws_list_all/blob/master/aws_list_all/introspection.py#L286
Then it's just a ton of heuristics and blacklists.
