### ISSUE TITLE
Route53

### ISSUE THREAD

**Issue by pwaller** [JohannesEbke/aws_list_all#4]
One apparent omission seems to be route53. It would be useful to get a complete list of domains.

**Comment by pwaller** [comment]
So I was able to make it list `HostedZones`, but for record sets we need to supply the zone. I guess this enumerating the zones is not yet supported?

**Comment by JohannesEbke** [comment]
Currently aws-list-all only lists "first-level" resources, that can be found without resorting to querying with parameters. Discovering second-level resources would also be interesting, I guess given the boto3 metadata and the level of coherence in the API it should be possible.

**Comment by JohannesEbke** [comment]
One reason route53 was not in the list is that boto3 get_available_regions returns the empty set for the "route53" service :disappointed: 

For v0.5, I've implemented a more exhaustive approach to service/region mapping, and added some mitigations for false positives. In short, I'm using the existence of an endpoint DNS entry as a guide, and then deal better with false positives (regions where a service is not (yet) supported).
