### ISSUE TITLE
Is it still up to date?

### ISSUE THREAD

**Issue by ramazansancar** [JohannesEbke/aws_list_all#56]
Are Regions and Services still up to date?

- [Available Regions and Zones](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html)
- [AWS RDS Regions, Availability Zones, and Local Zones](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html)

**Comment by lululemon-harry** [comment]
wondering the same, and if there is a way to limit resource checks to a specific AWS account ID

**Comment by iainelder** [comment]
@ramazansancar aws_list_all depends on the [botocore service model](https://botocore.amazonaws.com/v1/documentation/api/latest/tutorial/index.html).

> The `botocore` package is mainly data-driven. Each service has a JSON description which specifies all of the operations the service supports, all of the parameters the operation accepts, all of the documentation related to the service, information about supported regions and endpoints, etc. Because this data can be updated quickly based on the canonical description of these services, it’s much easier to keep `botocore` current.

When you install aws_list_all it will get the latest botocore version, today `1.29.163`.

```console
$ pip install aws-list-all
Collecting aws-list-all
  Downloading aws_list_all-0.9.2-py2.py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 1.8 MB/s eta 0:00:00
Collecting app-json-file-cache>=0.2.2 (from aws-list-all)
  Downloading app_json_file_cache-0.2.2-py2.py3-none-any.whl (6.1 kB)
Collecting boto3>=1.26.7 (from aws-list-all)
  Downloading boto3-1.26.163-py3-none-any.whl (135 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.9/135.9 kB 4.1 MB/s eta 0:00:00
Collecting appdirs (from app-json-file-cache>=0.2.2->aws-list-all)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting botocore<1.30.0,>=1.29.163 (from boto3>=1.26.7->aws-list-all)
  Downloading botocore-1.29.163-py3-none-any.whl (11.0 MB)
...
```

@lululemon-harry as far as I know aws_list_all scans only one account at a time. The target account depends on the profile or credentials you set in your environment. You can check the target account with [`aws sts get-caller-identity`](https://docs.aws.amazon.com/cli/latest/reference/sts/get-caller-identity.html).

**Comment by ramazansancar** [comment]
@iainelder Thank you for the information
